services:
  # Backend API Service
  - type: web
    name: pms-backend
    runtime: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: pms-postgres
          property: connectionString
    healthCheckPath: /api/dashboard/summary

  # Frontend Static Site
  - type: web
    name: pms-frontend
    runtime: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: pms-postgres
    databaseName: pms_dashboard
    user: pms_user
    plan: free